project:
  type: website

website:
  title: "paxnomada"
  repo-url: "https://github.com/ksilberb/paxnomada"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: LICENSE.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    code-tools: true

execute:
    freeze: auto
