project:
  type: website

website:
  title: "paxnomada"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "Stream"
        href: stream.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
