

# Sunday, March 09, 2025, 12:22PM

Lately I have been contemplating what I want to do after I graduate from UCSC next quarter. I have been here for four years and have had such a broad spectrum of things that I took interest in while I was here. When I project myself into the future I see so many possibilities its hard to really pin-point what I should focus on first. I know for sure I want to be a scientist and pursue knowlege, but in what area of science? I've been thinking about robotics, bioinformatics and computational genomics, marine biology and ecology, perhaps even machine learning.

I'm always scheming on ideas. Like the other day I was sure I wanted to just drop everything I'm doing and just become a kelp farmer or vertical greenhouse farming. I know I want to do something impactful and that has meaning, but on the other hand I also have that adventurous itch that I need to scratch that makes me want to just sell everything I own, buy a boat and sail around the world for a couple years. It feels so cliche to say all this, but its so real.

# Saturday, March 08, 2025, 10:34PM

I created this website to document my thoughts, projects, and perhaps even create a portfolio of all the things that I want to learn. I want to post pictures that I take with my new camera on here. Publish coding projects, etc.
